apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphql-server
  name: graphql-server
  namespace: k8s-demo
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: graphql-server
  sessionAffinity: None
  type: ClusterIP
