apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: service-test
  namespace: k8s-demo
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: service-test
  targetCPUUtilizationPercentage: 50
